### ISSUE TITLE
Where do we put code for registering instance?

### ISSUE THREAD

**Issue by rokj** [kumuluz/kumuluzee-health#1]
Where do we put HealthRegistry.getInstance().register(GithubHealthCheck.class.getSimpleName(), new GithubHealthCheck());

in which file?

**Comment by skrjanec** [comment]
Hello.

At the startup of your application you need to register your health checks. This can be done in 2 ways:

- You can use the @Health annotation to define health check classes.
- You can implement health check classes and register them manually.

All health check classes implemented in accordance to the first way will be registered automatically. However, implementing health check classes in the second way will require manual registration. As described above, you will want to register your health checks at the startup of your application. There is no specific file you have to put the code into, but one way to register your health checks is in a CDI bean which starts on application startup. See the example code below:

```java
package com.kumuluz.ee.samples.health;

import com.kumuluz.ee.health.HealthRegistry;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.context.Destroyed;
import javax.enterprise.context.Initialized;
import javax.enterprise.event.Observes;

@ApplicationScoped
public class HealthCheckRegistrationBean {

    private void initialize(@Observes @Initialized(ApplicationScoped.class) Object init) {
        HealthRegistry.getInstance().register(GithubHealthCheck.class.getSimpleName(), new GithubHealthCheck());
    }

    private void cleanup(@Observes @Destroyed(ApplicationScoped.class) Object init) {
    }
}

```

**Comment by rokj** [comment]
Hi, thank you for quick answer.

But where is CDI bean located? Where do we put this code?
