### ISSUE TITLE
Properties file

### ISSUE THREAD

**Issue by BaptisteMeynier** [kumuluz/kumuluzee-health#8]
Hello,
You provide lot of awesome out-of-the-box checks which work well with config.yaml. In microprofile config specification I think that the only supported format is microprofile-config.properties file.
I'm trying to load your checks like this in microprofile-config file:
```
kumuluzee.health.checks[0].data-source-health-check.type = liveness
kumuluzee.health.checks[0].data-source-health-check.jndi-name = jdbc/FishsDS
kumuluzee.health.checks[1].data-source-health-check.type = liveness
kumuluzee.health.checks[1].disk-space-health-check.threshold = 10000
```
It does not work. I don't know if I did a mistake with the properties key or this is not supported.
I know that these out-of_the-box checks are not a part of health specification.

Regards

**Comment by cen1** [comment]
Hi

the problem is that extension tries to find the key called `kumuluzee.health.checks.data-source-health-check` in a properties file. Property files have no notion of nested keys so it does not find it. This should probably be handled better by the extension by searching for existence of key prefixes.

Current workaround, just define an empty root:
```
kumuluzee.health.checks.data-source-health-check =
kumuluzee.health.checks.data-source-health-check.type = liveness
kumuluzee.health.checks.data-source-health-check.jndi-name = jdbc/CustomersDS
kumuluzee.health.checks.data-source-health-check.connection-url = jdbc:postgresql://localhost:5432/customers
kumuluzee.health.checks.data-source-health-check.username = postgres
kumuluzee.health.checks.data-source-health-check.password = postgres
```

**Comment by Jamsek-m** [comment]
Hi,
another thing worth trying is removing indexes from config keys. `kumuluzee.health.checks` is a map, not an array.

**Comment by BaptisteMeynier** [comment]
Thx for your reactivity !
It's work well with an empty entry
```
kumuluzee.health.checks.data-source-health-check =
kumuluzee.health.checks.data-source-health-check.type = liveness
kumuluzee.health.checks.data-source-health-check.jndi-name = jdbc/FishsDS
```
I read the content of the class DataSourceHealthCheck, more precisely method getConnection()

Is it possible to check more than 1 datasources for example jdbc/FishsDS and jdbc/StoreDS ?

**Comment by cen1** [comment]
Looks like only one datasource is supported out of the box. Opened https://github.com/kumuluz/kumuluzee-health/issues/9

**Comment by urbim** [comment]
The empty entry workaround should not be needed anymore since 2.4.4.
